# Generated by Django 5.1.1 on 2024-09-15 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='Batman', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_bride', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_groom', models.CharField(blank=True, max_length=150, null=True)),
                ('father_bride', models.CharField(blank=True, max_length=150, null=True)),
                ('father_groom', models.CharField(blank=True, max_length=150, null=True)),
                ('wedding_day', models.DateField()),
                ('weekend_only', models.BooleanField(default=False)),
                ('min_guests', models.IntegerField()),
                ('max_guests', models.IntegerField()),
                ('foreign_guests', models.IntegerField()),
                ('foreign_languages', models.CharField(blank=True, max_length=200, null=True)),
                ('program_languages', models.CharField(blank=True, max_length=200, null=True)),
                ('accommodation_guests', models.IntegerField()),
                ('transport_airport', models.BooleanField(default=False)),
                ('transport_after', models.BooleanField(default=False)),
                ('wedding_location', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('indoor_outdoor', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('any', 'No Preference')], max_length=100)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('homemade_alcohol', models.BooleanField(default=False)),
                ('homemade_food', models.BooleanField(default=False)),
                ('bride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bride_wedding', to='agency.client')),
                ('groom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groom_wedding', to='agency.client')),
            ],
        ),
        migrations.CreateModel(
            name='WeddingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.service')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.wedding')),
            ],
        ),
    ]
