# Generated by Django 5.1.1 on 2024-09-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_service_remove_client_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='Вашето име / Your name', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='Фамилия / Last name', max_length=200),
        ),
    ]
