# Generated by Django 5.1.1 on 2024-09-20 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_remove_wedding_father_bride_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='bride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bride_wedding', to='agency.client'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='groom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groom_wedding', to='agency.client'),
        ),
    ]
