# Generated by Django 5.1.1 on 2024-09-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_alter_wedding_bride_alter_wedding_groom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='accommodation_guests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='foreign_guests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='indoor_outdoor',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('any', 'No Preference')], max_length=100),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='wedding_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='wedding_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
